# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ca1262bb40b3176e34d90148fa3b497f683c54e5e64728da2997b8d51e1fbedfc5b0b40ab4ab756a3a176f2cc79251608570f71228c035089b34d63ce1628a5

test:
  secret_key_base: 73a6248f472751bf6b8ed81d1b33125acadad3a3ddc2e8432e4a25f271737279585c46b5a9fb02a2c4a340e60ee9ed3ef80f2a615e1c226de296efcb2b3e1e76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
